spring:
  application:
    name: live-chat-cloud

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

server:
  port: 8080
  servlet:
    context-path: /live-chat

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
